// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class KollakundvagnTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() 
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();

        driver.Manage().Cookies.DeleteAllCookies();
    }
  [TearDown]
  protected void TearDown() 
    {
        driver.Quit();
    }
  [Test]
  public void kollakundvagn() 
    {
        driver.Navigate().GoToUrl("https://www.inet.se/");
        driver.Manage().Window.Size = new System.Drawing.Size(1861, 1050);
        driver.FindElement(By.CssSelector(".form-control")).Click();
        driver.FindElement(By.CssSelector(".form-control")).SendKeys("4302202");
        driver.FindElement(By.CssSelector(".form-control")).SendKeys(Keys.Enter);
        Assert.That(driver.Title, Is.EqualTo("Samsung 980 PRO M.2 NVMe SSD 1TB - Inet.se"));
        driver.FindElement(By.CssSelector(".btn-buy")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        //WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(5));
        //IWebElement firstResult = wait.Until(e => e.FindElement(By.CssSelector(".price-col:nth-child(3) > .price")));
        Assert.That(driver.FindElement(By.CssSelector(".price-col:nth-child(3) > .price")).Text, Is.EqualTo("1 849 kr"));
        Assert.That(driver.FindElement(By.CssSelector(".freight > .price-col")).Text, Is.EqualTo("0 kr"));
        Assert.That(driver.FindElement(By.CssSelector(".qty-selector > label")).Text, Is.EqualTo("1"));
        driver.FindElement(By.CssSelector(".tabs li:nth-child(3)")).Click();
        Assert.That(driver.FindElement(By.CssSelector(".t1cke9b5")).Text, Is.EqualTo("Töm kundvagnen"));
        driver.FindElement(By.CssSelector(".btn-danger")).Click();
        Assert.That(driver.FindElement(By.CssSelector(".empty-cart > h1")).Text, Is.EqualTo("Din kundvagn är tom"));
    }
}
