// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CreateAccountCheckerroronemptyTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void createAccountCheckerroronempty() {
    driver.Navigate().GoToUrl("https://www.inet.se/");
    driver.Manage().Window.Size = new System.Drawing.Size(1811, 992);
    driver.FindElement(By.CssSelector(".user > .text-nowrap")).Click();
    driver.FindElement(By.LinkText("Skapa konto")).Click();
    driver.FindElement(By.CssSelector(".btn-success")).Click();
    var elements = driver.FindElements(By.CssSelector(".row:nth-child(5) > .col-xs-12:nth-child(2)"));
    Assert.True(elements.Count > 0);
  }
}
