// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class MenuCheckCategoriesTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void menuCheckCategories() {
    driver.Navigate().GoToUrl("https://www.inet.se/");
    driver.Manage().Window.Size = new System.Drawing.Size(1800, 992);
    driver.FindElement(By.ClassName("agx7mup")).Click();
    var elements = driver.FindElements(By.LinkText("Bildskärm"));
    Assert.True(elements.Count > 0);
    var elements1 = driver.FindElements(By.LinkText("Datorer"));
    Assert.True(elements1.Count > 0);
    var elements2 = driver.FindElements(By.LinkText("Dator­komponenter"));
    Assert.True(elements2.Count > 0);
    var elements3 = driver.FindElements(By.LinkText("Datortillbehör"));
    Assert.True(elements3.Count > 0);
    var elements4 = driver.FindElements(By.LinkText("Extern Lagring"));
    Assert.True(elements4.Count > 0);
    var elements5 = driver.FindElements(By.LinkText("Hem/Fritid/Hälsa"));
    Assert.True(elements5.Count > 0);
    var elements6 = driver.FindElements(By.LinkText("Kablar/Adaptrar"));
    Assert.True(elements6.Count > 0);
    var elements7 = driver.FindElements(By.LinkText("Ljud/Bild"));
    Assert.True(elements7.Count > 0);
    var elements8 = driver.FindElements(By.LinkText("Mobiltelefon"));
    Assert.True(elements8.Count > 0);
    var elements9 = driver.FindElements(By.LinkText("Nätverk"));
    Assert.True(elements9.Count > 0);
    var elementsa = driver.FindElements(By.LinkText("Presentkort"));
    Assert.True(elementsa.Count > 0);
    var elementsb = driver.FindElements(By.LinkText("Programvara"));
    Assert.True(elementsb.Count > 0);
    var elementsc = driver.FindElements(By.LinkText("Skrivare/Scanner"));
    Assert.True(elementsc.Count > 0);
    var elementsd = driver.FindElements(By.LinkText("Smarta Hem"));
    Assert.True(elementsd.Count > 0);
    var elementse = driver.FindElements(By.LinkText("Spel/Konsol/VR"));
    Assert.True(elementse.Count > 0);
    var elementsf = driver.FindElements(By.LinkText("Surfplatta"));
    Assert.True(elementsf.Count > 0);
    var elementsg = driver.FindElements(By.LinkText("Kampanjer"));
    Assert.True(elementsg.Count > 0);
    var elementsh = driver.FindElements(By.LinkText("Fyndhörnan"));
    Assert.True(elementsh.Count > 0);
    var elementsi = driver.FindElements(By.LinkText("Tävlingar"));
    Assert.True(elementsi.Count > 0);
    var elementsj = driver.FindElements(By.CssSelector("li:nth-child(20) .item-button"));
    Assert.True(elementsj.Count > 0);
    var elementsk = driver.FindElements(By.LinkText("Guider"));
    Assert.True(elementsk.Count > 0);
    var elementsl = driver.FindElements(By.LinkText("Datorbyggare"));
    Assert.True(elementsl.Count > 0);
  }
}
