// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class XiamiTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void xiami() {
    driver.Navigate().GoToUrl("https://www.webhallen.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1811, 992);
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("333044");
    driver.FindElement(By.CssSelector(".form-control")).SendKeys(Keys.Enter);
    driver.FindElement(By.LinkText("Xiaomi Mi Body Composition Scale 2")).Click();
    driver.FindElement(By.CssSelector(".text-btn:nth-child(3) > span")).Click();
    driver.FindElement(By.CssSelector(".stretch-y")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".free-shipping-info > span")).Text, Is.Not.EqualTo("Fri frakt tillgängligt!"));
  }
}
